version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./.docker/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - refactor-katas
  php-fpm:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./.docker/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - refactor-katas

networks:
  refactor-katas:
    driver: bridge